### ISSUE TITLE
docker 重新部署宝塔问题

### ISSUE THREAD

**Issue by wuweiit** [zhuoqi-chen/baota-panel#1]
1、 重新部署后导致etc/init.d下的命令全部失效；
2、重新up安装后导致php服务不能正常运行；

**Comment by zhuoqi-chen** [comment]
@wuweiit  重新部署是什么意思呢?能否贴出复现步骤?

**Comment by wuweiit** [comment]
docker-compose down
docker-compose up
这样就是重新部署容器，挂载目录的数据是最新的安装了mysql、php、tomcat环境。但是新部署的读取到的www下的数据也是安装了mysql、php、tomcat的，新的环境usr/bin,user/local数据被重刷了，导致的问题。

**Comment by zhuoqi-chen** [comment]
宝塔面板的所有配置,数据库都在/www目录下
我在容器中安装宝塔之前,已经提前将www目录共享出来,再安装的宝塔面板.所以仓库中的/www目录数据是宝塔面板自身启动所需的文件和配置文件.
把这个目录共享,目的为了让所有宝塔的所有数据(宝塔配置,装的环境,网站数据)可以持久化.
如果你不想持久化数据,直接取消volumes也是可以启动的,每次都是得到新的宝塔面板
但是容器删除,你的配置和代码就都没有了
不需要持久化:docker-compose.yml修改为如下:
```bash
baotamiaban:
  image: chenzhuoqi/baota:centos7.2-98617c88
  ports:
    - 20:20
    - 21:21
    - 80:80
    - 443:443
    - 888:888
    - 8888:8888
  privileged: true
  command: bash /bootstrap.sh
```
如果你想持久化mqsql数据库和网站代码,你可以设置volumes如下,再安装mysql
```bash
baotamiaban:
  image: chenzhuoqi/baota:centos7.2-98617c88
  ports:
    - 20:20
    - 21:21
    - 80:80
    - 443:443
    - 888:888
    - 8888:8888
  volumes:
    - ./www/server/mysql:/www/server/mysql
    - ./www/wwwroot:/www/wwwroot
  privileged: true
  command: bash /bootstrap.sh
```
还有宝塔好像有docker化的打算,可以关注官方团队!
https://www.bt.cn/bbs/forum.php?mod=viewthread&tid=6510&highlight=docker
希望能帮到你!

**Comment by wuweiit** [comment]
感谢，这个问题让宝塔团队解决最好了。
